name: 🌘 Deprecation and Removal (DEPR) Ticket
description: Per OEP-21, use this template to begin the technology deprecation process.
title: "[DEPR]: <Technology Name>"
labels: ["DEPR"]
body:
  - type: markdown
    attributes:
      value: |
        Refer to [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more detail on the deprecation and removal process. This ticket should only be used for proposing the removal of an Open edX technology.
        Please leave [DEPR] in the title of your ticket!
  - type: input
    id: rfc-start-date
    attributes:
      label: RFC Start Date
      description: The start date of the RFC (Request for Comments). Use the day you will announce this DEPR ticket on discourse (possibly today).
      placeholder: "2025-01-15"
    validations:
      required: true
  - type: input
    id: accept-date
    attributes:
      label: Target Plan Accepted Date
      description: When is the target date for getting the proposal reviewed and accepted? A good default is approximately 2 weeks from when the RFC is communicated (see [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html)).
      placeholder: "2025-01-29"
    validations:
      required: true
  - type: input
    id: transition-unblocked-date
    attributes:
      label: Target Transition Unblocked Date
      description: When is the target date for having a replacement ready, and unblocking operators for preparing for the final breaking change? See [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more details.
      placeholder: "2025-03-15"
    validations:
      required: true
  - type: input
    id: breaking-change-unblocked-date
    attributes:
      label: Earliest Breaking Changes Unblocked Date
      description: When is the earliest date you may make breaking changes? A good default is the later of 6 months after the RFC Start Date, or 1 month after the Target Transition Unblocked Date. This date can be negotiated as part of the RFC process. 
      placeholder: "2025-07-15"
    validations:
      required: true
  - type: input
    id: named-release-without
    attributes:
      label: Earliest Open edX Named Release with Breaking Changes
      description: What is the earliest named release without the breaking changes? Choose the first release cut date after the Earliest Breaking Changes Unblocked Date. Named releases are generally CUT in early April and early October. Use "Ulmo - 2025-10", "Verawood - 2026-04" as examples. Please reach out to the Build Test Release working group (#wg-build-test-release in Slack) if you're not sure.
      placeholder: "Ulmo - 2025-10"
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain, in a few sentences, why this technology should be removed - what's the usage pattern? What's wrong with keeping it around?
    validations:
      required: true
  - type: textarea
    id: removal
    attributes:
      label: Removal
      description: Include a description with links to what exactly is being removed.
    validations:
      required: true
  - type: textarea
    id: replacement
    attributes:
      label: Replacement
      description: Include a description with links to what this is being replaced by.
    validations:
      required: true
  - type: textarea
    id: deprecation
    attributes:
      label: Deprecation
      description: If you plan to mark the code for deprecation, explain how.
    validations:
      required: false
  - type: textarea
    id: migration
    attributes:
      label: Migration
      description: If automated migration will be needed, explain your migration plan.
    validations:
      required: false
  - type: textarea
    id: addl-info
    attributes:
      label: Additional Info
      description: If there is any additional publicly sharable information or data from your earlier analysis, include that.
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: Task List
      description: A list of tasks needed to deprecate or remove this feature and complete the DEPR.
      placeholder: "- [ ] Task 1 needed to deprecate or remove this feature."
    validations:
      required: false
