name: 🌘 Deprecation and Removal (DEPR) Ticket
description: Per OEP-21, use this template to begin the technology deprecation process.
title: "[DEPR]: <Technology Name>"
labels: ["DEPR"]
body:
  - type: markdown
    attributes:
      value: |
        Refer to [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more detail on the deprecation and removal process. This ticket should only be used for proposing the removal of an Open edX technology.
        Please leave [DEPR] in the title of your ticket!
  - type: input
    id: rfc-start-date
    attributes:
      label: RFC Start Date
      description: The start date of the RFC (Request for Comments). Use the day you will announce this DEPR ticket on discourse (possibly today).
      placeholder: "2025-01-15"
    validations:
      required: true
  - type: input
    id: accept-date
    attributes:
      label: Target Plan Accepted Date
      description: When is the target date for getting the proposal reviewed and accepted? A good default is approximately 2 weeks from the RFC Start Date (see [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html)).
      placeholder: "2025-01-29"
    validations:
      required: true
  - type: input
    id: transition-unblocked-date
    attributes:
      label: Target Transition Unblocked Date
      description: What is an estimated target date for unblocking operators for their transition tasks in preparation for any final breaking change? Where a replacement is required, the replacement must be ready. See [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more details.
      placeholder: "Estimated March or April 2025"
    validations:
      required: true
  - type: input
    id: breaking-change-unblocked-date
    attributes:
      label: Earliest Breaking Changes Unblocked Date
      description: When is the earliest date you may make breaking changes? A good default is the later of 6 months after the RFC Start Date, or 1 month after the Target Transition Unblocked Date. This date can be negotiated as part of the RFC process. See [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more details.
      placeholder: "Later of 2025-07-15 or the actual Transition Unblocked Date + 1 month"
    validations:
      required: true
  - type: dropdown
    id: named-release-without
    attributes:
      label: Earliest Open edX Named Release with Breaking Changes
      description: What is the earliest named release without the breaking changes? Choose the first release cut date after the Earliest Breaking Changes Unblocked Date. Approximate dates are listed below; for exact dates, see the [release schedule](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule) or reach out to the Build Test Release working group (#wg-build-test-release in Slack).
      options:
        - Ulmo - 2025-10
        - Verawood - 2026-04
        - W - 2026-10
        - X - 2027-04
        - Y - 2027-10
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain, in a few sentences, why this technology should be removed - what's the usage pattern? What's wrong with keeping it around?
    validations:
      required: true
  - type: textarea
    id: removal
    attributes:
      label: Removal
      description: Include a description with links to what exactly is being removed.
    validations:
      required: true
  - type: textarea
    id: replacement
    attributes:
      label: Replacement
      description: Include a description with links to what this is being replaced by.
    validations:
      required: true
  - type: textarea
    id: deprecation
    attributes:
      label: Deprecation
      description: If you plan to mark the code for deprecation, explain how.
    validations:
      required: false
  - type: textarea
    id: migration
    attributes:
      label: Migration
      description: If automated migration will be needed, explain your migration plan.
    validations:
      required: false
  - type: textarea
    id: addl-info
    attributes:
      label: Additional Info
      description: If there is any additional publicly sharable information or data from your earlier analysis, include that.
    validations:
      required: false
  - type: textarea
    id: transition-unblocked-tasks
    attributes:
      label: Task List
      description: A list of tasks needed to move the ticket to Transition Unblocked. This includes any task required to unblock operators for their transition tasks in preparation for any final breaking change. Where a replacement is required, this includes tasks for completing the replacement. See [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more details.
      placeholder: "- [ ] Task 1 needed to deprecate or replace this feature."
    validations:
      required: false
  - type: textarea
    id: removal-tasks
    attributes:
      label: Task List
      description: A list of tasks needed to remove this feature and complete the DEPR.
      placeholder: "- [ ] Task 1 needed to remove this feature."
    validations:
      required: false
