# Run ShellCheck on PRs and $default-branch

# For more context, see:
# https://github.com/openedx/.github/blob/master/docs/decisions/0001-shellcheck.rst

name: ShellCheck

on:
  pull_request:
  push:
    branches:
    - $default-branch

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:

    - name: Check out this repository
      uses: actions/checkout@v3

    - name: Check out shared actions
      uses: actions/checkout@v3
      with:
        repository: openedx/.github
        path: ./openedx-dot-github

    - name: Run ShellCheck!
      uses: ./openedx-dot-github/.github/actions/shellcheck
      with:

        # Required arguments for the ShellCheck action:
        root-dirs: "./scripts ./.github"

        # Optional arguments:
        #shellcheck-version: "v0.9.0"
        #shellcheck-options: ""
