# Run ShellCheck on PRs and $default-branch

# For more context, see:
# https://github.com/openedx/.github/blob/master/docs/decisions/0001-shellcheck.rst

name: ShellCheck

on:
  pull_request:
  push:
    branches:
    - $default-branch

permissions:
  contents: read

jobs:
  shellcheck:
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    uses: openedx/.github/.github/workflows/shellcheck.yml@master
    with:
      # For details on the meaning of each of these arguments, see:
      # https://github.com/openedx/.github/blob/master/.github/workflows/shellcheck.yml
      root-dirs: "./scripts ./.github"
      operating-system: "${{ matrix.os }}"
      #shellcheck-version: "v0.9.0"
      #shellcheck-options: ""
